# Berichte

## Meeting 1
**6. November 2024 --- 13:00 Uhr --- DOR24 Raum 1401 & online**

- Besprechung der Orga
- Besprechung möglicher Themen: vor allem praxisorientierte Arbeit mit verschiedenen LLMs und Tools, informeller Austausch, aber auch Texte lesen und Forschung diskutieren
- Wie können wir unsere Erkenntnisse, Fragestellungen und Ressourcen am besten festhalten? Über Moodle? Oder eine Website?: Sarah setzt Website über Quarto und Git auf und erstellt ein README file, so dass alle an der Website mitwirken können. Wenn jemand kein Interesse daran hat, kann sie/er Infos an Sarah schicken und sie baut es ein.
- Website muss nicht publik gemacht werden
- Wir möchten auch ein Wiki aufsetzten
- Erste Diskussion zu nützlichen Tools und Ressourcen (auf Website vermerkt)
- Haben wir die Möglichkeit einen Artikel in Interspeech zu publizieren? Mögliche Fragestellung: Wie geht Whisper mit dem genderneutralen Suffix um? 


## Meeting 2
**20. November 2024 --- 13:00 Uhr --- DOR24 t.b.a und online**

Zum Treffen werden zwei Texte gelesen: 

- *Hey ASR System! Why aren't you more inclusive?* von Ngueajio & Washington (2022) - [Link](https://arxiv.org/pdf/2211.09511)
- *Challenges of German Speech Recognition: A Study on Multi-ethnolectal Speech Among Adolescents* von Schubert, Duran & Siegert (2024) - [Link](https://www.isca-archive.org/interspeech_2024/schubert24_interspeech.pdf)

